### ISSUE TITLE
Multiple input destroy issue

### ISSUE THREAD

**Issue by sinankeskin** [dmuneras/ember-place-autocomplete#105]
I have 2 autocomplete inputs on my page. If I destroy (simply remove the component from the page) one of them the other one doesn't work until the remove and replace again.

I believe the issue relevant with elementId. I can't add an id to inputs also.

Thank you.

**Comment by dmuneras** [comment]
Hi, just to let you know that I already read it and I will reach you back when I have a chance to take a look (~tomorrow).

**Comment by sinankeskin** [comment]
Thank you.

**Comment by dmuneras** [comment]
Hi @sinankeskin, 

Feel free to reopen the issue in case the problem is not fixed for you. 

Best regards,
Daniel.

**Comment by sinankeskin** [comment]
I tried. Everythings perfect.

Thank you again.
