### ISSUE TITLE
Anyone have issues with the 'focusOutCallback' handler?

### ISSUE THREAD

**Issue by tshuck** [dmuneras/ember-place-autocomplete#13]
In ember 2.4.1, handling the 'focusOutCallback' seems to cause the google auto-suggest API to fail to pick up clicking on a place (because the action does not bubble to the browser, I guess?) although it still works if you arrow down and select and item with the enter key:
![handled](https://cloud.githubusercontent.com/assets/664467/13782704/364d542e-ea96-11e5-88a3-6891960350a7.gif)

But if you let it bubble (or just don't handle it at all), ember is cranky:
![unhandled](https://cloud.githubusercontent.com/assets/664467/13782722/48e68614-ea96-11e5-95a0-650a8c7ee19a.gif)

I read in the [docs](https://guides.emberjs.com/v2.4.0/templates/actions/#toc_allowing-default-browser-action) that you can preventDefault in an inline action handler, but this is using the 'send' action from the component

```
 this.get('handlerController').send(actionName, this.get('autocomplete').get('place'));
```

and I can't figure out how to get this to work:
a:  with send
b:  by telling Ember to ignore this one
c:  refactor to a better pattern than `send`

Any help would be appreciated.  Thanks!

**Comment by borisrorsvort** [comment]
Same issue too, this selection only works with arrows using the latest ember version

**Comment by borisrorsvort** [comment]
@dmuneras Any idea on how to solve this?

**Comment by mimie** [comment]
Hi boyz?! I have the same issues please help

**Comment by dmuneras** [comment]
@borisrorsvort  let me take a look.

**Comment by ofridagan** [comment]
+1
The autocomplete became unusable in latest Ember version.
BTW, it happens for me even without focusOutCallback.
If I click on the selection box - it gets stuck on the screen with no way to close.
If I use arrow keys and enter it works.

**Comment by ofridagan** [comment]
was able to fix this with:
https://github.com/dmuneras/ember-place-autocomplete/pull/17

**Comment by dmuneras** [comment]
@ofridagan  I published your fix, thanks a lot, I hope it works for everyone.

**Comment by ofridagan** [comment]
👍
