### ISSUE TITLE
Add a Demo app.

### ISSUE THREAD

**Issue by esbanarango** [dmuneras/ember-place-autocomplete#16]

**Comment by bobvdvalk** [comment]
yeah hurry up with this. As someone new to Ember it's hard to understand.

**Comment by dmuneras** [comment]
Hey @bobvdvalk, you  are right.  

In the meantime, if you have a question don't hesitate to ask. 

Best regards,
Daniel.

**Comment by dmuneras** [comment]
Done! https://dmuneras.github.io/ember-place-autocomplete/
