### ISSUE TITLE
Overwrite templates

### ISSUE THREAD

**Issue by allthesignals** [dmuneras/ember-place-autocomplete#23]
It's not possible to overwrite the place-autocomplete-field.hbs to do something like change the "placeholder" attribute. Is there a way to do this in the templates? I know there is a workaround, but this seems to be the most common pattern.

Some notes on the structure for allowing this: https://github.com/ember-cli/ember-cli/issues/4587

**Comment by dmuneras** [comment]
Hi, 

Thanks, Let me take a look.

Regards, 
Daniel.

**Comment by dmuneras** [comment]
@allthesignals Sorry for the suuuper late response. 

It is possible, you can pass a block, the autocomplete is going to be added to the first input in the passed HTML
