### ISSUE TITLE
Tabindex -1?

### ISSUE THREAD

**Issue by pedro** [dmuneras/ember-place-autocomplete#25]
Hey folks!

Why is the autocomplete input tabindex set to `-1`?

I just manually set it to 0 so the input behaves normally as far as tabs/ordering goes.

**Comment by dmuneras** [comment]
Hi @pedro 

To be honest, someone else add that value to the tabindex attr, I was looking for a reason to set it to `-1` and I didn't find it. So, I am putting `0`as default value.

Regards,
Daniel.
