### ISSUE TITLE
Latest version not released (exclude parameter)

### ISSUE THREAD

**Issue by arthur5005** [dmuneras/ember-place-autocomplete#33]
Hey, was scratching my head about the 'exclude' parameter I read in the documentation not working, and then realized that it's because those changes haven't been replaced. Is there something you're waiting on?

A

**Comment by dmuneras** [comment]
Hey @arthur5005 

Let me check why it is not released.

Best regards,
Daniel.

**Comment by esbanarango** [comment]
@arthur5005 Last version is out!

**Comment by arthur5005** [comment]
Thanks man!! :)
