### ISSUE TITLE
Possible to pass in the google keys outside of the config?

### ISSUE THREAD

**Issue by brancusi** [dmuneras/ember-place-autocomplete#37]
Hi,

I would like to send over the google keys after the user is authenticated, is this something that could be done? I see the google api is setup on app load.

Thanks

**Comment by dmuneras** [comment]
Hi @brancusi,

I think it is possible by loading again `//maps.googleapis.com/maps/api/js` after you have the user credentials, it should override the previous import and override the `google.maps` variable. You have to construct again the url using the user credentials ( similar as I do it in https://github.com/dmuneras/ember-place-autocomplete/blob/master/index.js )

(I am not sure if I understood the question correctly)

Daniel.
