### ISSUE TITLE
Can't use ember-place-autocomplete component in acceptance tests

### ISSUE THREAD

**Issue by arthur5005** [dmuneras/ember-place-autocomplete#41]
Trying to use the component in an acceptance test caused this exception:

```
Assertion failed: You have turned on testing mode, which disabled the run-loop's autorun. 
You will need to wrap any code with asynchronous side-effects in an Ember.run
```

This guide was helpful in figuring out what the heck was going on:
http://discuss.emberjs.com/t/guide-asynchronous-side-effects-in-testing/2905

Opened up a pull request: #40 
This wraps the `place_changed` handler in a run loop.

**Comment by dodeja** [comment]
Thanks @arthur5005.
