### ISSUE TITLE
Cannot read property 'maps' of undefined

### ISSUE THREAD

**Issue by franklington** [dmuneras/ember-place-autocomplete#43]
Getting this. 

```
Uncaught TypeError: Cannot read property 'maps' of undefined
    at Class.getAutocomplete (place-autocomplete-field.js:76)
    at Class.setupComponent (place-autocomplete-field.js:49)
    at invoke (ember.debug.js:339)
    at Queue.flush (ember.debug.js:407)
    at DeferredActionQueues.flush (ember.debug.js:531)
    at Backburner.end (ember.debug.js:601)
    at ember.debug.js:1167
```

i guess because google api isn't loaded at the time.

ember-cli: 2.10.0
node: 4.5.0

**Comment by mattwagar** [comment]
Having this issue too. How did you resolve this?

ember-cli: 2.14.1
node: 6.10

**Comment by dmuneras** [comment]
Hey @mattwagar,

Let me take a look today at night. 

Best regards,
Daniel.

**Comment by mattwagar** [comment]
I have the API Key for Google Places in my environment.js, and copied your component into my template.hbs. Do I need to initialize window.google anywhere?

**Comment by mattwagar** [comment]
Did you look into this?

**Comment by franklington** [comment]
Sry for my late response. I wish had documented the error more precisely because I don't know how i solved it.  What is your setup for the component? Do you have a code example?

This is how my environment.js looks like
```
    contentSecurityPolicy: {
      'script-src': "'self' 'unsafe-eval' apis.google.com' *.googleapis.com maps.gstatic.com",
      'frame-src': "'self' https://*.firebaseapp.com'",
      'connect-src': "'self' wss://*.firebaseio.com https://*.googleapis.com' maps.gstatic.com"
    },
    'place-autocomplete':{
      exclude: false,
      key: 'XXXXXXXXXXXXXXXX'
    },
```
My Template:
 ```
  {{#place-autocomplete-field
                  value= address
                  disable=false
                  handlerController= this
                  classNames='ui right icon input'
                  inputClass= 'place-autocomplete--input '
                  focusOutCallback='placeDone'
                  placeChangedCallback='placeChanged'
                  types='address'
                  restrictions= autocompleteRestrictions
                  withGeoLocate= true
                }}
                        {{input value=value
                              classBinding="inputClass"
                              tabindex=tabindex
                              disabled=disabled
                              bubbles=true}}
                          <i class="marker icon"></i>

  {{/place-autocomplete-field}}
```

**Comment by dmuneras** [comment]
Hey @mattwagar  and @franklington Sorry, I had to do a server migration, so, I didn't have enough time to actually fix the problem. I have an idea about what is happening. I am going to try to fix the problem today.

**Comment by dmuneras** [comment]
@franklington, could you check the network tab of your google inspector to check if the request to the google inspector is being made, the client id is present and the request result is a success?

**Comment by franklington** [comment]
@dmuneras what do u mean with request to GI? The authentication to the google server, if that is what you want to know, response is successful. 

BTW the code I posted belongs to the 0.0.17 release. I saw that some things have changed.

**Comment by dmuneras** [comment]
Hey @franklington and @mattwagar,

I was doing some updates and fixes. I think your problem should be fixed now. I am going to release a new version now to let you review if that fix your problem. 

Best regards,
Daniel.

**Comment by mattwagar** [comment]
Hello @dmuneras,

Sorry for the lack of response. I upgraded to version 0.0.20 and it works! 

However, in your documentation you should explain what "exclude: boolean" means in the environment.js. When I switched it to false like @franklington suggested, the autocomplete worked.

Best,
Matt

**Comment by dmuneras** [comment]
@mattwagar  I am glad everything is working for you now. It should work even if you don't use `exclude` option.

**Comment by grapho** [comment]
@dmuneras I am having a very similar error when writing acceptance tests

cannot set property `maps` of undefined...

It looks like `window.google` is not being initialized in test land

**Comment by dmuneras** [comment]
Hey @grapho,

Still happening with the last version?

**Comment by dmuneras** [comment]
@grapho  You have to mock the Google API when testing, I added a section to the documentation web site to show you how I do it: https://dmuneras.github.io/ember-place-autocomplete/tests/mocks
