### ISSUE TITLE
Default places type option should be no option instead of 'geocode'

### ISSUE THREAD

**Issue by Floby** [dmuneras/ember-place-autocomplete#48]
I Spent a little too much time on this issue trying to figure out what was going wrong :D

I don't think it's safe to assume users of this addon only need `geocode` results. It seems to me that this component should:

+ use an empty array as default option for the `types` parameter for Places Autocomplete
+ allow `types` to be an array of strings
+ allow `types` to be a string (same as current)

If this makes sense, I'm happy to open a PR

**Comment by dmuneras** [comment]
You are right, feel free to open the PR. It will be well received. :)
