### ISSUE TITLE
Push latest version to bower

### ISSUE THREAD

**Issue by Falibur** [dmuneras/ember-place-autocomplete#50]
Hi,

Can you push/register the latest version to bower so my package.json can be just referring to a version :)

Thnx!

**Comment by dmuneras** [comment]
Sure, will be released by tomorrow.

**Comment by Falibur** [comment]
thnx!

**Comment by dmuneras** [comment]
@Falibur I had an emergency at work. I have to do some updates before release, it is going to be done by next week. Sorry if i am causing you any inconvenience.

**Comment by dmuneras** [comment]
Good morning @Falibur 

I already publish a new version to npm (0.0.18)

Let me know if it works for you,
Daniel.
