### ISSUE TITLE
Interested in ability to enable/disable autocomplete from property?

### ISSUE THREAD

**Issue by PeterCadwell** [dmuneras/ember-place-autocomplete#55]
What does `disabled` attribute do in the component? I'd like for a way to enable/disable this component via the `disabled` property.

**Comment by dmuneras** [comment]
Hey @PeterCadwell,

You can pass the disabled params (set as true) and the input is going to be disabled. It is just the common `disabled` option of the Ember `input` helper:

```js  
   {{place-autocomplete-field
    value= model.address2
    handlerController= this
    inputClass= 'place-autocomplete--input-2'
    inputId='place-autocomplete--input-2'
    placeChangedCallback="placeChangedSecondInput"
    restrictions=restrictions
    disabled=true -> THIS ONE
  }}
``` 

https://cl.ly/2W2i1g2l2L3y

**Comment by dmuneras** [comment]
BTW, @PeterCadwell  you give an idea, maybe if the input is disabled, the component should stop listening to the google events...

**Comment by jakiestfu** [comment]
@dmuneras We'd like to add support for that logic. Would you accept a PR for this?

**Comment by dmuneras** [comment]
@jakiestfu sure!, you can implement it and I  will be glad to review it and merge it.

**Comment by dmuneras** [comment]
I am going to close this, we already addressed the question and we are waiting for the contribution. :D
