### ISSUE TITLE
Set search bounds with component attributes.

### ISSUE THREAD

**Issue by ppegusii** [dmuneras/ember-place-autocomplete#56]
Hi @esbanarango @dmuneras, thanks for this addon. Are you interested in the ability to set the bounds of the search via attributes passed in to the component?

**Comment by dmuneras** [comment]
@ppegusii we already have something implemented related with it thanks to @earayo But I think it doesn't allow you to manually pass the bounds. @earayo do you want to implement this and take the glory?

**Comment by dmuneras** [comment]
Close because of the contribution of @ppegusii https://github.com/dmuneras/ember-place-autocomplete/pull/57
