### ISSUE TITLE
Possible to enter a value not in results list?

### ISSUE THREAD

**Issue by adambedford** [dmuneras/ember-place-autocomplete#58]
Is it possible for a user to enter a value that isn't in the results list? For example, say this is a search for job locations, would it be possible to enter "Remote" as an option?

**Comment by dmuneras** [comment]
Hey @adambedford!

I just take a look at this case and it seems to work, the value is sent to the callback function so, you can use it.

![screen shot 2017-09-08 at 6 31 30 pm](https://user-images.githubusercontent.com/344518/30234575-fbe9e5fc-94c3-11e7-9625-01fb5811264b.png)

The object sent is the one at the bottom of the image, { 'name': 'fake-address' }, you can use it in your `placeChangedCallback `

If you have any problem let me know or it doesn't work for you like it is working for me, let me know.

Daniel.

**Comment by dmuneras** [comment]
Hi @adambedford,

I am closing the issue, but, if you need more information or help, let me know.

Best regards,
Daniel.
