### ISSUE TITLE
I think the readme should be updated for clarity

### ISSUE THREAD

**Issue by kamikaz1k** [dmuneras/ember-place-autocomplete#59]
I think the README should be updated to be crystal clear with what is happening.
It too me a bit of time to get it up and running after digging through issues.

How to use in HBS
```
{{place-autocomplete-field
  ...
}}

For more types look under: https://developers.google.com/places/web-service/supported_types
```

How to setup ENV
```
ENV['place-autocomplete'] = {
  exclude: true, // true means library wont include the maps script | false means it will
  key: 'AIZ...', // Your API Key from the google console
  client: 'gme-myclientid', // Client ID if necessary
  version: 3.27, // Optional - if client is set version must be above 3.24
  language: 'en', // Optional - be default will be based on your browser language
  region: 'GB' // Optional
};

You can get an API key from here: https://developers.google.com/places/web-service/autocomplete
```

Also, thank you for making this. Honestly, it saved me a tonne of time. :)

**Comment by dmuneras** [comment]
Hey @kamikaz1k, 

You are completely right. I started to work on a documentation website to make more clear the setup of the addon. I am going to update the README tomorrow to help people while the documentation website is ready.

Best regards,
Daniel.
