### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by nielsrask** [dmuneras/ember-place-autocomplete#60]
I may be doing something wrong, but nothing happens when I insert text into the input field. I can't see any call to Google's API. And no autocomplete is generated. Weird.

What action is supposed to be used to call the Google API?

**Comment by dmuneras** [comment]
Hey @nielsrask,

* Could you tell me which version of Ember are you using? 
*  If you are using the google service without a key, Could you check if the google service is blocking your request? (check the network tab of your google inspector).
* Could you attach an image of the console of element inspector to check if any error is displaying?

Best regards,
Daniel.

**Comment by dmuneras** [comment]
Hey @nielsrask,

Could you take a look at this: https://github.com/dmuneras/ember-place-autocomplete/wiki/Getting-Started Maybe you have the same problem that other person report.

**Comment by nielsrask** [comment]
We built an endpoint on our API server instead, since we couldn't get this
working.

Mvh,



*Niels Rask*

0734-100 450  | niels.rask@prodentor.se

www.prodentor.se | 556935-2726



2017-11-09 22:10 GMT+01:00 Daniel Múnera Sánchez <notifications@github.com>:

**Comment by dmuneras** [comment]
Glad you fix the problem you have. Sad that you could get the addon working in your project, if you want give it a try with the information on the wiki page. 

I am going to close issue this because it is not enough information to know what happen.
