### ISSUE TITLE
Assertion Failed: Cannot call set with 'address' on an undefined object.

### ISSUE THREAD

**Issue by onewiseburdman** [dmuneras/ember-place-autocomplete#61]
Recreated your example:

I keep getting the following.  It's not very clear what to do, I would really appreciate a demo.  If someone else has experienced this can someone please help me?  
Assertion Failed: Cannot call set with 'address' on an undefined object.

If I update the value=model.address I get the same error,

if I just change it to value=address I get no errors but I also receive nothing back at all from google.

**Comment by dmuneras** [comment]
@onewiseburdman  I am going to close this since it was addressed in the other issue you opent: `https://github.com/dmuneras/ember-place-autocomplete/issues/62`
