### ISSUE TITLE
put an example that actually works

### ISSUE THREAD

**Issue by onewiseburdman** [dmuneras/ember-place-autocomplete#62]
I am still at this-there was a PR that someone created a semiworking example but even that has issues.  It's very frustrating-I'm not a developer per se, I rely on working examples.  Which you have none.  Perhaps you could just take the 5 minutes of time and re-create it with a working model.  You reference a controller which I didn't have.  The other guys did - but didn't have a component.  

I really just need to get the lat-long from an address.

**Comment by dmuneras** [comment]
Hey @onewiseburdman,

You are right, let me write in the README the complete step by step to get a working example.

It is going to be available tomorrow around this hour is that is ok.

Best regards,
Daniel.

**Comment by dmuneras** [comment]
## General comment

I just wrote a simple wiki page to try to help you to setup a working example: 

https://github.com/dmuneras/ember-place-autocomplete/wiki/Getting-Started

Would be more helpful if you can point me to a repo with your code, or an snippet, or something, it is kind of complicate to figure it out what is happening without having more information. 

## About the controller

The `handlerController` is not a mandatory property. If you pass an action to the `placeChanged` callback, it is going to execute the action.  Indeed, the only fields that are mandatory to get something working are the `value` property and the `placeChangedCallback`.

```javascript

  {{place-autocomplete-field
    value= model.address
    placeChangedCallback=(action "placeChanged")
  }}

```
The example above works.

Hope that is helpful, if not, I would love to help you if you put more information about this issue as comments here.

Best regards,
Daniel.

**Comment by onewiseburdman** [comment]
Thank you-so far it works now.  Ultimately what I need to do is look up an address get lat long and concatenate it to another url that does a json request.  

So by  logic concerns:

I get the Lat Long from address
Then post that data to another page that uses ember data to return that information
From that ember data goes to firebase and sets a query.  I am sure for other people its super simple-but its not for me.

So in order:

Enter Form data to transpose Address to Lat Long.  Check-Working with your awesome code.

Then take that data concatenate it to a get json request from a third party website.  

Post that data to a new page where ember data does a query against firebase data (basically filters).

You helped me get to the first part.  Now I will work on the next part.  I believe as the placechangedcallback is set I can create an action that will do the next thing for me.   It's awesome you were super responsive- I really appreciate that more than you know.  If you have any pointers on how to accomplish any of the latter parts I really appreciate that too.  I am learning a lot and can't thank you enough.

Many Thanks,

Chris

**Comment by dmuneras** [comment]
Glad this help you Chris, you can do what you want using the information you get in the callback function. You are in the right path i am sure you are going to get what you want pretty soon.

**Comment by onewiseburdman** [comment]
A couple of things for you to clarify for the readme:

On the User Model in order for the placeholder text to read as the placeholder- one should set the fake-model data as follows:  
  address: DS.attr('string',{defaultValue: ''}) . otherwise its just going to read like the default value data says.  

Also if one doesn't fix the formatting of the component one would continue to see action errors-simple enough to fix as demonstrated.  {{place-autocomplete-field
    value= model.address
    handlerController= this
    inputClass= 'place-autocomplete--input'
    focusOutCallback= done
    placeChangedCallback= placeChanged
    placeholder= "Custom placeholder"
  }}

**Comment by yefan15** [comment]
When I declare  placeChangedCallback=(action "placeChanged") I get TypeError: Cannot read property 'apply' of undefined. and when I use  placeChangedCallback='placeChanged' it doesn't get called. Is there something I need to do special if I am creating a search bar component that is going to be used else where?
