### ISSUE TITLE
Can creation of script tag be deferred until page load?

### ISSUE THREAD

**Issue by tansongyang** [dmuneras/ember-place-autocomplete#68]
First of all, I'm an Ember newbie, so please forgive and correct any misconceptions I have.

Basically, we have a situation where we **have** to add the Google Maps API key after the client has loaded. This is because of some details of our build process which we can't change. For example, sometimes we'll build in production mode but still deploy to a testing environment, and we don't want to use our production key in this case. However, we do load the page with bootstrap data, which will contain the desired key.

It looks like the script tag is being generated at build time right now ([`index.js`](https://github.com/dmuneras/ember-place-autocomplete/blob/99ccb6a8ccaee3dbe7a05be9b2504eaf96f6cba8/index.js#L6)). Is there currently any way to defer this? If not, would you accept a PR to add that functionality?

**Comment by dmuneras** [comment]
Hey @tansongyang,

Is there currently any way to defer this? If not, would you accept a PR to add that functionality?

Yes! as the README says:


> You can supply your own Google API key or client ID in config/environment.js. You may also choose to exclude the Google API from the page if it is already loaded in your app. You may also choose to set the specific version of the google api.
 
```javascript
ENV['place-autocomplete'] = {
  exclude: true,
  key: 'AIZ...',
  client: 'gme-myclientid',
  version: 3.27, // Optional - if client is set version must be above 3.24
  language: 'en', // Optional - be default will be based on your browser language
  region: 'GB' // Optional
};
``` 

If you do this, you should handle the loading of the google maps library yourself, but, you will have all the freedom to do it as you want.

This could be helpful: https://github.com/dmuneras/ember-place-autocomplete/pull/32

Let me know if that is helpful,
Daniel.

**Comment by tansongyang** [comment]
Ah, thanks for pointing that out. Would you take a PR to extract the function that currently builds the script tag into an exportable function? I'd like to avoid copy-pasting.

**Comment by dmuneras** [comment]
Sure!! it will be great!!! I can created and I can take a look tomorrow.

**Comment by tansongyang** [comment]
Thank you! Let me know if you want any input on it.
