### ISSUE TITLE
Send optional parameters data in request

### ISSUE THREAD

**Issue by szsoppa** [dmuneras/ember-place-autocomplete#7]
Is there any way to set optional parameters data when sending request to google ? I'm interested only in retrieving citites and as documentation says it requires from me to set `types=(cities)` in optional request paramater. It would be nice to have this possibility.

**Comment by dmuneras** [comment]
@szsoppa at the moment we are not allowing you to set that parameter, I am going to add that option, seems to be very useful.

Regards, 
Daniel.

**Comment by esbanarango** [comment]
@szsoppa You're now able to set the `types` on the version `0.0.9`

````js

{{place-autocomplete-field
  value= model.address
  disable=false
  handlerController= this
  focusOutCallback='done'
  placeChangedCallback='placeChanged'
  types='locality administrative_area_level_1 locality' // <--
}}
