### ISSUE TITLE
After update ember 3.1.2, inputClass doesn't appear

### ISSUE THREAD

**Issue by devCaso** [dmuneras/ember-place-autocomplete#70]
I just to update to 3.1.2 and strangely the css class passed through inputClass attribute doesn't appear but instead there a white space. Someone knows if it is an error related with the upgrade?

Thanks!

**Comment by dmuneras** [comment]
Hey @devCaso,

Let me double check today or tomorrow and reach you back.

Best regards,
Daniel.

**Comment by devCaso** [comment]
@dmuneras thanks you very much because your soon response but it was my fault, I didn't see that I had duplicated the inputClass attribute and the second was inputClass=' ' I'm so sorry :)

By another hand, this mistake didn't overwrite the attribute value in the previous version (3.0), because this was the confusion.

I close this issue, thanks again :)

**Comment by dmuneras** [comment]
@devCaso thanks for taking the time to double check. I am glad you solved your problem
