### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by jamesdixon** [dmuneras/ember-place-autocomplete#72]
Hi, any chance a new release gets pushed to npm soon?

**Comment by dmuneras** [comment]
Sure, I completely forgot to do it. I am AFK, but I am going to create a new release once I go back home.

**Comment by jamesdixon** [comment]
thx @dmuneras!

**Comment by dmuneras** [comment]
Hey @jamesdixon! I released a new version. Thanks a lot for your contribution.

**Comment by jamesdixon** [comment]
thank you!
