### ISSUE TITLE
Fix Acceptance Tests instructions in Readme

### ISSUE THREAD

**Issue by algodave** [dmuneras/ember-place-autocomplete#73]
The Google Places Autocomplete mocked object in Readme is missing the `setOptions()` function, which is present in addon's tests' [google-place-autocomplete-object](https://github.com/dmuneras/ember-place-autocomplete/blob/master/tests/helpers/google-place-autocomplete-object.js)

Hope this helps someone else saving time! 🙂

**Comment by dmuneras** [comment]
Hey @algodave!

Thanks a lot for reporting this. I am going to update the README to point to the actual mock.

Best regards,
Daniel.
