### ISSUE TITLE
Deprecation on latest Ember

### ISSUE THREAD

**Issue by engwan** [dmuneras/ember-place-autocomplete#75]
DEPRECATION: Please refactor `{{input focus-out="focusOut"}}` to `{{input focus-out=(action "focusOut")}}. ('ember-place-autocomplete/templates/components/place-autocomplete-field.hbs'

**Comment by dmuneras** [comment]
👌

**Comment by dmuneras** [comment]
https://github.com/dmuneras/ember-place-autocomplete/pull/77

**Comment by dmuneras** [comment]
Hey @engwan, 

I made that small change and publish a new version 1.0.1. Let me know if the WARNING still appearing after using the new version.

Best regards,
Daniel.
