### ISSUE TITLE
placeChangedCallback and focusOutCallback actions not being called 

### ISSUE THREAD

**Issue by yefan15** [dmuneras/ember-place-autocomplete#76]
When I declare placeChangedCallback=(action "placeChanged") I get TypeError: Cannot read property 'apply' of undefined. and when I use placeChangedCallback='placeChanged' it doesn't get called at all. Is there something I need to do special if I am creating a search bar component that is going to be used else where? The logic for the action is defined in my component js file.  I am also noticing the same behavior with the focusOutCallback

Here is a snippet: 

```hbs
Template (search-bar-address):

<p id=“message”>Message: {{message}}</p>

<p>Full adddress from JSON sent to the callback: {{{fullAddress}}}</p>

<p>Clean string: {{cleanFullAddress}}</p>

<p> Model address: {{address}}</p>

<div id=“search-bar” data-google-auto="{{googleAuto}}">

<label class=“visually-hidden” for=“input-search”>Add a new address</label>

{{place-autocomplete-field

id=“input-search”

value= address

handlerController= this

placeholder=“Add a new address”

inputClass= ‘place-autocomplete–input’

placeChangedCallback= “addressChanged”

focusOutCallback=“done”

restrictions=googleMapsRestrictions

withGeoLocate= true

}}

<pre style=“font-size: 6px;”>

{{placeJSON}}

</pre>


googleMapsRestrictions: { country: ‘us’, }, 
fullAddress: null, 
googleAuto: null,
 action: { done()
{ console.log(“Reached”); }, 
addressChanged(place) { console.log("***********"+place);

  }
}

Where it is implemented

 {{search-bar-address
          id="search-bar-component"
          }}
```

**Comment by dmuneras** [comment]
Hey @yefan15,

It is a little bit complicate to read the code you pasted, but, I created this simple gist that show you how to use it. It looks super simple, but it should work: 

https://gist.github.com/dmuneras/1f0de66d2240c862537cb49372804acf

Basically, as long as you have defined the action in the component it should work. As personal comment, just try to avoid using that `handlerController`, I made a big mistake adding that when I create this project and it is very likely that I am going to remove it in the near future. 

Let me know if this help you.

Best regards,
Daniel.

**Comment by yefan15** [comment]
@dmuneras Thanks for that. One I did notice when i try to grab the value of what is in the search bar it only brings back what the user types unless I click in the testbox itself. So if I type in 123 and let google find places near me and select on of those options, let's say 123 Albany Way. When I do this.get('address') I only get the 123 value back unless I click within the text box then I would get that full value.

**Comment by yefan15** [comment]
@dmuneras Thanks for that. One I did notice when i try to grab the value of what is in the search bar it only brings back what the user types unless I click in the testbox itself. So if I type in 123 and let google find places near me and select on of those options, let's say 123 Albany Way. When I do this.get('address') I only get the 123 value back unless I click within the text box then I would get that full value.

**Comment by yefan15** [comment]
Yes Daniel this was very helpful, thanks so much!

**Comment by dmuneras** [comment]
No problem @yefan15, I am glad it helped you.
