### ISSUE TITLE
Issue with using inside component

### ISSUE THREAD

**Issue by ChristopherJohnson25** [dmuneras/ember-place-autocomplete#78]
Is anyone else having issues with this getting used inside a component? The network calls are getting made, but it seems like the actions aren't working properly. I have not been able to get the autocomplete dropdown, been working on this for awhile too..

**Comment by dmuneras** [comment]
Hey @ChristopherJohnson25!

Could you give me a bit more information about what is happening to you? It could be something simple like a gist like this one: https://gist.github.com/dmuneras/1f0de66d2240c862537cb49372804acf


It could be very helpful if you tell me which version of Ember you are using.

Best regards,
Daniel.

**Comment by ChristopherJohnson25** [comment]
Thanks Daniel, I'm on Ember 3.04. 

Here is my code..

```
              {{place-autocomplete-field
                inputClass= 'form-control'
                placeChangedCallback=(action 'placeChanged')
                types="(cities)"
                placeholder='Enter your city...'
                value=city
              }}
              <div class="place-response">
                {{placeResponse}}
              </div>
```

```
    placeChanged(place) {
      this.set('placeResponse', place);
      console.log(this.get('placeResponse'));
    },
```


All in component template and js files.

**Comment by ChristopherJohnson25** [comment]
Just debugged this, it was a z-index issue. Apologies for the premature issue.

**Comment by dmuneras** [comment]
No problem @ChristopherJohnson25! your issue report is much appreciated. 

Best regards,
Daniel.

**Comment by ChristopherJohnson25** [comment]
I'll leave this closed in case it's an easy problem. Is there a simple way to get Lat, Long for the autocompleted city?
