### ISSUE TITLE
Latitude and Longitude on City

### ISSUE THREAD

**Issue by ChristopherJohnson25** [dmuneras/ember-place-autocomplete#79]
Is there a simple way to get latitude and longitude from the city response? I see a key in the object but it's formatted a bit weird..

**Comment by ChristopherJohnson25** [comment]
Does anyone have any info on this? I'd love for this to work, but I'm worried I may have to switch to another solution for this...

**Comment by dmuneras** [comment]
Hey @ChristopherJohnson25,

This addon is a wrapper of the Google Places API. So, the addon the information you can get is the one google provides: https://developers.google.com/places/web-service/details

Could you share in a gist  how you use your addon in the template and your callback function?

Best regards,
Daniel.

**Comment by dmuneras** [comment]
@ChristopherJohnson25 just by looking really quick I got this:

![screen shot 2018-10-10 at 3 53 05 pm](https://user-images.githubusercontent.com/344518/46765477-b9e07d00-cca4-11e8-8f0b-a3a0aa2b7205.png)

**Comment by ChristopherJohnson25** [comment]
Worked perfectly! Thank you, I wouldn't have thought to do that.

**Comment by dmuneras** [comment]
Cool!! so nice it worked for you! I am going to close the issue then.
