### ISSUE TITLE
(Just a question)  Is there a way to customize the pac container if you are using it multiple places? 

### ISSUE THREAD

**Issue by yefan15** [dmuneras/ember-place-autocomplete#80]
Is there a way to customize the pac container if you are using it multiple places? Currently I am overriding the styling of the google dropdown. I am using the places autocomplete multiple places but I do not want the styling to be applied everywhere just that specific template. Is there any way to accomplish this? I am also just using CSS and not SASS.

**Comment by dmuneras** [comment]
👍
