### ISSUE TITLE
Cannot read property 'getPlacePredictions' 

### ISSUE THREAD

**Issue by yusufsagdic** [dmuneras/ember-place-autocomplete#91]
Hi, I'm getting error when I try to this sample.
https://dmuneras.github.io/ember-place-autocomplete/usage/service

Cannot read property 'getPlacePredictions' of undefined

thanks.

**Comment by dmuneras** [comment]
Hey @yusufsagdic!

Are you sure the service is injected in the place where you are using it (`googlePlaceAutocompleteService: service('google-place-autocomplete')`)

Could you create a gist with the component/route/controller where you are testing the example?

Best regards,
Daniel

**Comment by yusufsagdic** [comment]
Hey @dmuneras, thanks for quick reply.
Here it is.
https://gist.github.com/yusufsagdic/5dc3a63734d6a345952c2c96850c7251

**Comment by dmuneras** [comment]
Hey @yusufsagdic!

I copied and pasted your code into one app, ran it and it worked for me 😅. The only thing I can think about is that it could be a problem with the google api key you are setting, maybe it doesn't have the maps api enabled.

It will be very helpful if you can copy here the complete error stack trace to have more information. 

You can check if running this into the console returns `undefined`or returns the actual Google API object: `new window.maps.places.AutocompleteService();`.

Best regards,
Danie.

**Comment by yusufsagdic** [comment]
Hey @dmuneras 

When I check console log 

> this.get(' googlePlaceAutocompleteService');

 return undefined.

thanks.

**Comment by yusufsagdic** [comment]
Hey @dmuneras 

Ember v. 3.8.0 and I'm working on localhost.

When I check the console for new window.maps.places.AutocompleteService() its return

> Cannot read property 'places' of undefined

When I check the browser console nothing load from google map api. Am I need to add  index.hmtl or anywhere like this script ? I just add to addon configure environment.js and  I used my last post gist.

> <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places&callback=initAutocomplete"
>         async defer></script>

**Comment by yusufsagdic** [comment]
Hey @dmuneras,
I copied the configurations for enviroment.js and I missed the exclude parameter true so its the big mistake :) 
Thank you so much.

**Comment by dmuneras** [comment]
Glad you solved your problem @yusufsagdic 😄
